name: Publish Helm Charts

on:
  push:
    # branches:
    #   - main
    paths:
      - "helm-charts/**"
      - ".github/workflows/publish-helm-charts.yaml"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package charts
        run: |
          mkdir -p .deploy

          for chart in helm-charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm dependency update "$chart"
              helm lint "$chart"
              helm package "$chart" --destination .deploy
            fi
          done

      - name: Generate index.yaml
        run: |
          helm repo index .deploy \
            --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .deploy
          publish_branch: gh-pages